name: Sync Pull Request to Azure Boards
 uses: danhellem/github-actions-pr-to-work-item@1.2
  with:
    # Azure DevOps Personal Access Token
    ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}' 
    # Organization Name
    ado_organization: 'TraceableTribe'
    # Project Name
    ado_project: 'Agile'
    # Work Item Type (usually a custom work item type)
    ado_wit: 'User Story'
    # Closed State
    ado_close_state: 'Closed'
    # In Progress state that the PR will get set too after it is created
    ado_active_state: 'Active'
    ado_new_state: 'New'
